### ISSUE TITLE
Actualización.

### ISSUE THREAD

**Issue by vidimus** [V0r1an/La_Mascarada#2]
Hola, @V0r1an 

Hoy me han preguntado en un grupo de Telegram por si podía dar mi opinión sobre este escenario, que como es de los que se publicaron hace tiempo, no tiene habilitado el sistema de votación y comentarios que sí que tienen los nuevos. Así que eso me ha hecho escribir aquí. Me gustaría saber si tienes alguna intención de actualizar/mejorar tu escenario, aunque sólo fuese para activar la opción de recibir votos y comentarios (yo te podría ayudar con eso, es bastante sencillo, en realidad).

**Comment by V0r1an** [comment]
Hola!
Gracias por escribir... Pues la verdad es que fue mi primer escenario (así
que disculpar los gallos) y ya hace casi 4 años que no toco el programa y
no sabría ni por dónde empezar... Si fuera algo sencillo, lo haré encantado.
Un saludo y gracias!

**Comment by vidimus** [comment]
Hola, @V0r1an 

Gracias a ti por responder tan pronto. No sé si sigues por Valkyrie, pero ha cambiado bastante y ahora hay muchos escenarios en español, tanto traducidos como creados por autores españoles. En mi caso, llevo más de 40 escenarios traducidos al español (algunos con ayuda de otras personas o colaborando yo con sus traducciones).

Lo de añadir las opciones para votar/comentar tu escenario, puedo hacerlo yo sin problemas. Lo mío son las traducciones, pero es algo sencillo que ya he tenido que aprender. No recuerdo si tu escenario tenía algún fallo, pero lo podría mirar y tengo contacto con un creador de escenarios que podría echarle un ojo y reparar los fallos (a menos que sean muy gordos, que en ese caso no quiero abusar de su tiempo y su paciencia). Te pasaré los archivos para que sólo tengas que sustituir los de tu repositorio (también lo he hecho antes, así que es pan comido).

Si quieres, puedo añadir lo del formulario para empezar, y si quieres, una imagen en miniatura para la descripción (siempre llama más la atención). Supongo que el actualizar el escenario hará que la gente lo vuelva a jugar.

Una cosa más, tienes la posibilidad de compartir el repositorio con algún administrador de Valkyrie, de ese modo, si te quieres olvdar de tener que actualizar tú o hacerle algún tipo de mantenimiento, como puede ser una traducción, ellos se encargarían. Es una pena ver algunos escenarios abandonados por los autores que se van quedando relegados en el olvido.

Bueno, ya me contarás qué te parece y en un par de días puedo tener tu escenario listo para que lo jueguen y voten (te puedo explicar cómo ver los comentarios que te vayan dejando).

Un saludo.

**Comment by V0r1an** [comment]
Gracias a ti!
Claro! Haz lo que te apetezca... Esta para eso... La partida la hice para
la comunidad y es de "ella"... Cuando empecé fue porque veía un déficit de
partidas en castellano brutal (creo que estaba la pajarería y otra más)...
Así que todo lo que sea aportar (para mejorar), por mi perfecto!
Gracias de nuevo

**Comment by vidimus** [comment]
Vale, @V0r1an en un par de días me pongo y te envío el archivo.

**Comment by vidimus** [comment]
Bueno, al final he visto que sólo hay un final, y añadir el valor que activa el formulario ha sido muy sencillo.

@V0r1an, aquí tienes el fichero con los 3 archivos de tu escenario. Sólo tienes que descomprimirlo y sustituir a los antiguos. La apliación Valkyrie hará el resto actualizando la nueva versión del escenario.

Me he tomado la libertad de añadirle la línea de "sinopsis" para que salga con el título del escenario. Espero que no te importe, pero así queda un poco más visible.

[LaMascarada.zip](https://github.com/V0r1an/La_Mascarada/files/6096020/LaMascarada.zip)

**Comment by V0r1an** [comment]
Hola @vidimus!
Antes que nada, gracias por el tiempo dedicado a esto...
Me da un poco de vergüenza preguntar esto, pero... que tengo que hacer? :)
es que la partida la hice hace taaaanto tiempo, que no sé ni si conservaré
los programas para hacerlo :)

**Comment by vidimus** [comment]
@V0r1an simplemente descomprimir el zip y reemplazar con esos archivos los que tienes en este repositorio. Le das a subir los archivos en el repositorio, y como se llaman igual, los sustituye y ya está.

Unas horas después, la actualización aparecerá en valkyrie. Sin más.

**Comment by V0r1an** [comment]
Hola @vidimus !
Gracias por tu post...
Creo que ya está :)
Un Saludo y de nuevo, gracias

**Comment by vidimus** [comment]
@V0r1an , tienen que estar en el mismo sitio que los archivos antiguos. En este caso, dentro de la carpeta "La_Mascarada" de tu repositorio (y no fuera de él como están ahora.

**Comment by V0r1an** [comment]
Hecho!

**Comment by vidimus** [comment]
Perfecto, ya he visto que se ha actualizado. Ya sólo te falta que te animes a retomar el escenario o a hacer otro nuevo, @V0r1an
